
document.write("<!-- Navbar (sit on top) -->");
document.write("<div class=\"w3-top\">");
document.write("  <div class=\"w3-bar w3-light-blue w3-card\" id=\"myNavbar\">");
document.write("    <a href=\"https:\/\/ths-robotics.github.io\/#home\" class=\"w3-bar-item w3-button w3-wide w3-hover-cyan\"><img src=\"media\/landscape_logo_thsr.png\"alt=\"logo\" height=\"24px\"><\/a>");
document.write("    <!-- Right-sided navbar links -->");
document.write("    <div class=\"w3-right w3-hide-small\">");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/#about\" class=\"w3-bar-item w3-button w3-hover-cyan\">ABOUT THSR<\/a>");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/#team\" class=\"w3-bar-item w3-button w3-hover-cyan\"><i class=\"fa fa-user\"><\/i> OUR OFFICER TEAM<\/a>");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/gallery.html\" class=\"w3-bar-item w3-button w3-hover-cyan\"><i class=\"fa fa-th\"><\/i> IMAGE GALLERY<\/a>");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/sponsors.html\" class=\"w3-bar-item w3-button w3-hover-cyan\"><i class=\"fa fa-usd\"><\/i> SPONSORS<\/a>");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/blog.html\" class=\"w3-bar-item w3-button w3-hover-cyan\"><i class=\"bi bi-megaphone-fill\"><\/i> ANNOUNCEMENTS<\/a>");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/important_links\" class=\"w3-bar-item w3-button w3-hover-cyan\"><i class=\"bi bi-link\"><\/i> IMPORTANT LINKS<\/a>");
document.write("      <a href=\"https:\/\/ths-robotics.github.io\/#get_involved\" class=\"w3-bar-item w3-button w3-hover-cyan\"><i class=\"bi bi-chat-fill\"><\/i> GET INVOLVED<\/a>");
document.write("    <\/div>");
document.write("    <!-- Hide right-floated links on small screens and replace them with a menu icon -->");
document.write("");
document.write("    <a href=\"javascript:void(0)\" class=\"w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium\" onclick=\"w3_open()\">");
document.write("      <i class=\"fa fa-bars\"><\/i>");
document.write("    <\/a>");
document.write("  <\/div>");
document.write("<\/div>");
document.write("");
document.write("<!-- Sidebar on small screens when clicking the menu icon -->");
document.write("<nav class=\"w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large\" style=\"display:none\" id=\"mySidebar\">");
document.write("  <a href=\"javascript:void(0)\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-large w3-padding-16 w3-hover-cyan\">Close ×<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/#about\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">ABOUT THSR<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/#team\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">OUR OFFICER TEAM<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/gallery.html\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">IMAGE GALLERY<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/sponsors.html\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">SPONSORS<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/blog.html\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">ANNOUNCEMENTS<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/important_links\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">IMPORTANT LINKS<\/a>");
document.write("  <a href=\"https:\/\/ths-robotics.github.io\/#get_involved\" onclick=\"w3_close()\" class=\"w3-bar-item w3-button w3-hover-cyan\">GET INVOLVED<\/a>");
document.write("<\/nav>");
